title: Yalin's Research Blog
email: ylliu@hkmu.edu.hk
description: A blog and portfolio by Yalin Liu
theme: minima
baseurl: "" # Set to "/repo" if hosted at username.github.io/repo
url: "https://username.github.io" # Replace with your GitHub Pages URL
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
category_dir: categories
tag_dir: tags
collections:
  pages:
    output: true
    permalink: /:name
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
languages: ["en", "zh-CN", "zh-TW"]
default_lang: "en"
exclude_from_localization: ["css", "assets", "images", "js"]